url: https://infosecsapper.com
name: The Infosec Sapper
title: infosecsapper.com
description: Home of the Infosec Sapper
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!-- More -->

theme: jekyll-theme-minimal
